language: java

jdk:
  - oraclejdk8

env:
  global:
  - # ^^ OSSRH_JIRA_USERNAME
  - secure: GNqrfND00MzkPKETXOnrMNkodZ9I2K0/JkMNcrtGyzPVbDbSCPAeC5X5Z1/bkvtMq+TlzK9V6bwExI0Np5H7c/MbGg3phHQvPSsXbeStGTfvaOb+eVVd5v9Xi9KVFHeHMYEq/XmzFWlJzKKKM1bRllSUTcaQB0N3ZqrcyY4jNdYb9kIBjyH1RYAxt9qSWnu0mOjqjGRWapF5JWksA5GLRjCuGU7ldOp+1PcxggVEGOShTwCQB5SC7Sjgtf8VXizr1jDnGGlTBoOeQo/VtdUpHpRqPm2jYTUsf6Wn1mOFbi8vj5xvOxbTQ/5pi0mwQuChvGfk3qPUyL5paEv/WfO6u9Kh8T3RjLxEdMptakdRQh78hB9B4+J2bLexvkmbDdtlTdtSpIJ417mCsXQLzo4ip4se5EmHf6YbXghqN51wuy2fVmP0/k0Vihkl3wddoOdqoESfCj7ZX5q9HeLQ+RDwOB/wBTxdlUYITFz0ZAbkS1OldiY9v1PDlLPj/ANM5dPZC9tVaExHrKL//W55k82LcHZBL89DSZchim5JZih55KUGsNV8rPgdbR1+gZG2a5xwf0dQKA3aUTaepTgRj5+KhX9gittxN8LSReuvKNMZPJXsBDMml+kRkzTOBiz4r/VPyNscFirdUhZIRf4qHCha5bdKOXo8lgThGb7HDMrhA3Y=
  - # ^^ OSSRH_JIRA_PASSWORD
  - secure: UWub2C0/gUMVxjPryZStRP1F0+Fq1moR/Usua0g2BCD9TwBlk5O0JLUzGXcIdOv0cQNCZH7KfIyV0AgCuBr91mCneDqz2JosHqksrImcNT04L9r46xHLrHGkwkBAnXn39ATxKUFHaE+/PmzxjCSy2UphbmSzOtw7G+Bl9UqVe8xzrGgC5mpAHCvt5yBjZazlR9yK376MEMjrwEmCIy2jeRmx8nnieW3j2aRqq8Rm9V2LUOjGrfZji7o/hh8vsVaTSZJbVVHJu8p8Sj6Vd8AhUVgsBy1vToQXM+r3k4VVOOLF8KnAReJRC16aXs2ClntY3jz+l9rlWW3ZmWTqY9h+h9aH8lw3wrDxkEDbNGAkek+ywItYOmDtHEtBoolrcVwsYnrPhFGn2vHoFvNLUx3bHNXka4Jl/WvpI4NkEb0ra37N+g4020p75nWHDEccXFgI7fnfUdv4+02rBorCxZ8keWzJx/4pMIh94VkWXqp7h38IBUf77VGcbFl/jMR7NYe6DqUMt8CQOA4a4eCi8VyvclbLatOwIYQZtraZuVOjyCWRDa+wb10FDF/Dnh187glNWpt0m2hG2XbwyQq1/+YSn+YLRvQgqSLC4vHJVH3e4Wg5h+lkTOVpXsClPwEeJ8ieQYpS6lx4HuPmyd0DHaiwC5bmKTyUXvlgXVpQiUkUhbw=
  - # ^^ GPG_KEY_NAME
  - secure: lIlz6Q/iN1dpgRqlIuYsfcT/k93OimJCTs1iIZ7YoPIlvtH8QIZ3RQRQyxLZzIzOEWcrNZliCGxGxADyHNc3tJnrSsBeDw8g4maf3NLP/vHcLxgYkM9xoSy2a9sB3u3UzUI39gd+83catXLdBn9r3ymU3SOHd+JPUPVRK/1KGWrEog9wpKjZT3WXkoslg1XAG7owbumMrhFZZuKqxGcvj9BJjQBwUWrOsUGlK+k7f+XZig3bXcD/Cpiwieo8apePtCb3Oz/CGNYzwe4x7bL5RRl6OdAq4QUtNc//IahE9Oq2F10U97rksK0hwjFXGyQcF5z8Ki5d8WnSZ2vMTHugtDMOIO2DgJQO9P5XJPGQ0yxrd3sPpgWaCA+hkOE8/OlLVoqHD0OrZB/UNtRK0S2i5W159Wus1izLN4Tx7UxWZR5w3IMA2m/db7avDlDwG44ZuA3BSqRl9qf5ALqvHiwdfKskyobvBRSZO/4mJCthAT1iiOAV9fuD1cHZnXGoL2OxJMNg9zFt8tI2U4wSsdBhCLtTNgwJe2YSmiNb+9ZOKtcT1NUSUlOvUat8SruJ/zO8MmfQQwi1O24pZBVlIHeqW/9kz55iBrj+I8ATP3OgwhAXDMQDl1mlTkqM0mk2aEukv6qAcT/kw2BtGnFbvM1k4V4Szt6m8EtLO1xucNxp9Og=
  - # ^^ GPG_PASSPHRASE
  secure: "m/OeMp8BSdBSeBjwC25wt2s68Bmsoc+9qeOClOeRmy59jmcIMzUoZ/tr8eZNxmQzfSPMvDdwrJJgTHGX1NxMha4DdG2fBfwdQF1hdwf5d9s7rDSzITlxgLdsksKTprOgmHKXAA7Gohv8Qifqe62NQn9hWlAeuaWnhAL0BpzDcmGWfHVN7DZsvdTFNHADzS/llTEhlKQflAfyDh6HCyQaesrcCIV4FbUhP6uxbo3+uKqBz9oRAERfTIdkr9Ff4DSQMssK5BmKA2IcHunLCT5QiRWbFYf91oi7FkgbGSOMQwFs6uYzVzceJ2wHrZQjq74f4Sjb9CICIPUWHA7AWT3p9kZVG0y3xwyG+Hx8AfbJd2YesVXoalJKjQ0W5ZU2dUdoefr0LW9+0BREZnK34ysNGFz8i217WgvdL25z4AiZ79ezTtiAwH5QVWU7ty/aARg28D/+NhTO8O89/bHTSWX6J9Kze4nIGi0gzoSPpekw02awqJ9TqIG1FZyp8ZYKEoiRT79hW1WgTfq2KGBFUSN/ox8nzC8x9MMBGDob++3gNJ8OSzrhqF5jrx31CQdEUdf16v6oOc86Im2r1sIGjKg/aA6Dropr+ZVnFh9RIrIERJsFGhkOHk043tj1ZV9jW4VXSwbGx96vLP5v6sQnG1ZW+OFZ/px6qvDD97KR92EQhiE="

install: mvn install -P !build-extras -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - mvn test -P !build-extras -B
  # The below should be placed in the after_success stage but due to the nature on how travis deals with after_script
  # exit codes different than 0 would not affect the build result which is not the expectation in this case.
  - chmod +x ./travis-ci/before-deploy.sh
  - chmod +x ./travis-ci/deploy.sh
  - ./travis-ci/before-deploy.sh
  - ./travis-ci/deploy.sh

cache:
  directories:
    - ~/.m2/repository
