title: Pagerduty-client
description: Simple pager duty client with full integration with PagerDuty Events APIs v2
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
